### PR TITLE
Animations styles 

### PR DESCRIPTION
**Pull request by ofeterovskaya**

### CODE REVIEW

**Review by mattcarlotta — APPROVED** [review]
Wow Oksana, this is an amazing portfolio! I love seeing that you incorporated some of the extras like the mobile hamburger menu, the stylish font-awesome icons in the footer, and you even added some hover animations! Very cool! You spent a lot of time on your portfolio and it shows and it's paying off. Excellent work. 👍 

I've went through all of the code in the project and found a few minor things that you can **optionally** fix for the future: 
- Your section headline tags have low color contrast (light color on a light background). Low contrast can make text harder to read for those with vision impairment. Ideally, you'll want to aim for 5.0-7.0+ color contrast ratio to be web-accessible compliant. Not a huge deal, but something you can tweak if desired (here's a tool to [check color contrast](https://webaim.org/resources/contrastchecker/))
The screenshot below is using Firefox's "Accessibility" tab to check for Accessibility issues (there are plenty of other tools that work with Chrome that can display this information as well, such as the [Axe Dev Tools](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) extension)

- When writing CSS, it's best to avoid using properties that are browser specific. For example, [-webkit](https://github.com/ofeterovskaya/fenrir-intro/blob/bf6ea31af2a3e83ef22a0b66b17a583f6823440a/css/index.css#L68) is a browser specific property for Chrome and Safari. Unfortunately, it's not compatible with Firefox. This topic is a bit advanced, but what's great is that there is a very simple fix using this excellent online tool called [autoprefixer](https://autoprefixer.github.io/). It offers styles for all browsers! On the left, paste in your styles, and on the right, you'll get generated styles that will be compatible with most modern browsers. For example, if I were to take your styles that contain the -webkit property:
```css
#section1 img:hover{
    -webkit-transform: scaleX(-1);
    transform: scaleX(-1);
    animation-timing-function: ease-out;
    animation: mymove 5s infinite;
}
```
 and drop them into autoprefixer, I get the following results, which will ensure your portfolio looks the same **across all browsers**:
 ```css
#section1 img:hover{
    -webkit-transform: scaleX(-1);
    -ms-transform: scaleX(-1);
        transform: scaleX(-1);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    -webkit-animation: mymove 5s infinite;
            animation: mymove 5s infinite;
}
```
If you have questions about browser specific CSS properties, I'd be happy to go into more detail! Otherwise, as long as you're aware that they exist, you've already won half the battle.
- Be mindful when using [Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) that they have two outcomes: **success** and **fail**! For example, your [fetch code that retrieves Github project data](https://github.com/ofeterovskaya/fenrir-intro/blob/bf6ea31af2a3e83ef22a0b66b17a583f6823440a/js/index.js#L108-L119) is a promise that has two outcomes: success and fail. Currently, you're handling the success case (`.then`), but what happens if the request fails (`.catch`)!? This is quite an advanced topic, but knowing that a request can succeed or fail is important. If you'd like to see what another student did for their project, I'd recommend giving [my feedback](https://codethedream.slack.com/archives/C04NANXSH9Q/p1688778270057859?thread_ts=1688774744.232529&cid=C04NANXSH9Q) a quick read. It goes over the fail outcome and how you can `catch` it and display it in your website. The reason this is important is you want to convey that something was supposed to load, but it failed. If you show nothing and/or you log an error to the console, then it's not **visually** clear to a non-technical user that something failed to load. Imagine this scenario: You attempt to visit amazon.com. But no matter how many times you refresh the page, it's always blank. In this imaginary case, amazon is unable to load (fetch) product data, but is that clear to the user when all they can see is a blank white page? If not, how would you fix it?

**Comment by ofeterovskaya** [comment]
Thank you Matt for your review. I'll try to find new color for better contrast, you are right, that's crucial for people with vision impairment. Thanks for recommending autoprefixer, that's always great to learn something new. I would love to get links for  cross-browser styling(?)  Thanks for pointing to succeed or fail request, I'll take a closer look at this and will try to fix it.

**Comment by ofeterovskaya** [comment]
I don't know why images on my project section didn't upload well. Just 2 out of 6 upload correctly. On my "live view" everything is fine, but when I look through vercel link they re  broken. Also I need to find more info how to add alt to images through API

**Comment by mattcarlotta** [comment]
> I don't know why images on my project section didn't upload well. Just 2 out of 6 upload correctly. On my "live view" everything is fine, but when I look through vercel link they re broken. Also I need to find more info how to add alt to images through API

Double check your image name spelling! Image names are case sensitive, where `img/Landscape-Company.png` does not equal `img/landscape-company.png`!!!! Either match the image name to the project name OR use [toLowerCase](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLowerCase) on the image src attribute and ensure all of your image names are lower cased.

Before:
Screenshot from 2023-08-02 07-07-31

After:
Screenshot from 2023-08-02 07-07-44

**Comment by ofeterovskaya** [comment]
Thank you so much!

**Pull request merged**
